name: Require AI Log

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-ai-log:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Verify docs/AI_LOG.md updated when code changes
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA")

          echo "Changed files:\n$CHANGED_FILES"

          # 파일 변화가 있을 때 로그가 포함되었는지 검사 (문서/이미지 등은 제외)
          CODE_CHANGED=$(echo "$CHANGED_FILES" | grep -E "^(index.html|.*\\.(html|js|css)|vercel.json|render.yaml|server.js|package.json|package-lock.json|pages/|layout/|js/|css/|images/|mypage/|naver-keyword-tool/)" || true)
          LOG_CHANGED=$(echo "$CHANGED_FILES" | grep -E "^docs/AI_LOG.md$" || true)

          if [ -n "$CODE_CHANGED" ] && [ -z "$LOG_CHANGED" ]; then
            echo "❌ 작업 로그 누락: 코드가 변경되었지만 docs/AI_LOG.md가 수정되지 않았습니다."
            echo "코드 변경 목록:\n$CODE_CHANGED"
            exit 1
          fi

          echo "✅ AI 작업 로그 규칙 충족"

      - name: Summarize and deduplicate AI_LOG
        run: |
          node .github/scripts/ai_log_clean.js || true
